// =============================================================================
// Generated by efx_ipmgr
// Version: 2025.2.288
// IP Version: 1.0
// =============================================================================

////////////////////////////////////////////////////////////////////////////////
// Copyright (C) 2013-2025 Efinix Inc. All rights reserved.              
//
// This   document  contains  proprietary information  which   is        
// protected by  copyright. All rights  are reserved.  This notice       
// refers to original work by Efinix, Inc. which may be derivitive       
// of other work distributed under license of the authors.  In the       
// case of derivative work, nothing in this notice overrides the         
// original author's license agreement.  Where applicable, the           
// original license agreement is included in it's original               
// unmodified form immediately below this header.                        
//                                                                       
// WARRANTY DISCLAIMER.                                                  
//     THE  DESIGN, CODE, OR INFORMATION ARE PROVIDED “AS IS” AND        
//     EFINIX MAKES NO WARRANTIES, EXPRESS OR IMPLIED WITH               
//     RESPECT THERETO, AND EXPRESSLY DISCLAIMS ANY IMPLIED WARRANTIES,  
//     INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF          
//     MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR    
//     PURPOSE.  SOME STATES DO NOT ALLOW EXCLUSIONS OF AN IMPLIED       
//     WARRANTY, SO THIS DISCLAIMER MAY NOT APPLY TO LICENSEE.           
//                                                                       
// LIMITATION OF LIABILITY.                                              
//     NOTWITHSTANDING ANYTHING TO THE CONTRARY, EXCEPT FOR BODILY       
//     INJURY, EFINIX SHALL NOT BE LIABLE WITH RESPECT TO ANY SUBJECT    
//     MATTER OF THIS AGREEMENT UNDER TORT, CONTRACT, STRICT LIABILITY   
//     OR ANY OTHER LEGAL OR EQUITABLE THEORY (I) FOR ANY INDIRECT,      
//     SPECIAL, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OF ANY    
//     CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF      
//     GOODWILL, DATA OR PROFIT, WORK STOPPAGE, OR COMPUTER FAILURE OR   
//     MALFUNCTION, OR IN ANY EVENT (II) FOR ANY AMOUNT IN EXCESS, IN    
//     THE AGGREGATE, OF THE FEE PAID BY LICENSEE TO EFINIX HEREUNDER    
//     (OR, IF THE FEE HAS BEEN WAIVED, $100), EVEN IF EFINIX SHALL HAVE 
//     BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES.  SOME STATES DO 
//     NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR            
//     CONSEQUENTIAL DAMAGES, SO THIS LIMITATION AND EXCLUSION MAY NOT   
//     APPLY TO LICENSEE.                                                
//
////////////////////////////////////////////////////////////////////////////////

localparam MODE = 0;
localparam MASTER_NUM = 2;
localparam ADDR_WIDTH = 24;
localparam DATA_WIDTH = 32;
localparam REG_INPUT = 1'b1;
localparam REG_OUTPUT = 1'b1;
localparam OPT_LATENCY = 1'b0;
localparam DATA_WIDTH_DIV_8 = 4;
localparam PRIORITY_M00 = 1;
localparam PRIORITY_M01 = 2;
localparam PRIORITY_M02 = 3;
localparam PRIORITY_M03 = 4;
localparam PRIORITY_M04 = 5;
localparam PRIORITY_M05 = 6;
localparam PRIORITY_M06 = 7;
localparam PRIORITY_M07 = 8;
localparam PRIORITY_M08 = 9;
localparam PRIORITY_M09 = 10;
localparam PRIORITY_M10 = 11;
localparam PRIORITY_M11 = 12;
localparam PRIORITY_M12 = 13;
localparam PRIORITY_M13 = 14;
localparam PRIORITY_M14 = 15;
localparam PRIORITY_M15 = 16;
localparam PRIORITY_M16 = 17;
localparam PRIORITY_M17 = 18;
localparam PRIORITY_M18 = 19;
localparam PRIORITY_M19 = 20;
localparam PRIORITY_M20 = 21;
localparam PRIORITY_M21 = 22;
localparam PRIORITY_M22 = 23;
localparam PRIORITY_M23 = 24;
localparam PRIORITY_M24 = 25;
localparam PRIORITY_M25 = 26;
localparam PRIORITY_M26 = 27;
localparam PRIORITY_M27 = 28;
localparam PRIORITY_M28 = 29;
localparam PRIORITY_M29 = 30;
localparam PRIORITY_M30 = 31;
localparam PRIORITY_M31 = 32;
